version: '3.1'
services:
    wordpress:
        image: wordpress
        restart: always
        ports:
            - 7575:80
        environment:
            WORDPRESS_DB_PASSWORD: learning
        volumes:
            - "./wp-content:/var/www/html/wp-content"

    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: learning
        volumes:
            - "./data/mysql/wordpress:/var/lib/mysql"